[undollar]
src.github = "Freed-Wu/undollar"
fetch.github = "Freed-Wu/undollar"

[manpager]
src.github = "Freed-Wu/manpager"
fetch.github = "Freed-Wu/manpager"

[help2man]
src.pypi = "help2man"
fetch.pypi = "help2man"

[setuptools-generate]
src.pypi = "setuptools-generate"
fetch.pypi = "setuptools-generate"

[repl-python-wakatime]
src.pypi = "repl-python-wakatime"
fetch.pypi = "repl-python-wakatime"

[repl-python-codestats]
src.pypi = "repl-python-codestats"
fetch.pypi = "repl-python-codestats"

[translate-shell]
src.pypi = "translate-shell"
fetch.pypi = "translate-shell"

[autotools-language-server]
src.pypi = "autotools_language_server"
fetch.pypi = "autotools_language_server"

[bitbake-language-server]
src.pypi = "bitbake_language_server"
fetch.pypi = "bitbake_language_server"

[expect-language-server]
src.pypi = "expect-language-server"
fetch.pypi = "expect-language-server"

[mutt-language-server]
src.pypi = "mutt-language-server"
fetch.pypi = "mutt-language-server"

[pkgbuild-language-server]
src.pypi = "pkgbuild-language-server"
fetch.pypi = "pkgbuild-language-server"

[portage-language-server]
src.pypi = "portage-language-server"
fetch.pypi = "portage-language-server"

[requirements-language-server]
src.pypi = "requirements-language-server"
fetch.pypi = "requirements-language-server"

[sublime-syntax-language-server]
src.pypi = "sublime-syntax-language-server"
fetch.pypi = "sublime-syntax-language-server"

[termux-language-server]
src.pypi = "termux-language-server"
fetch.pypi = "termux_language_server"

[tmux-language-server]
src.pypi = "tmux-language-server"
fetch.pypi = "tmux-language-server"

[xilinx-language-server]
src.pypi = "xilinx-language-server"
fetch.pypi = "xilinx-language-server"

[zathura-language-server]
src.pypi = "zathura-language-server"
fetch.pypi = "zathura-language-server"

[mulimgviewer]
src.pypi = "mulimgviewer"
fetch.pypi = "mulimgviewer"

[g3kb-switch]
src.github = "lyokha/g3kb-switch"
fetch.github = "lyokha/g3kb-switch"
