[windows10-icons]
src.github = "B00merang-Artwork/Windows-10"
fetch.github = "B00merang-Artwork/Windows-10"

[windows10-themes]
src.github = "B00merang-Project/Windows-10"
fetch.github = "B00merang-Project/Windows-10"

[undollar]
src.github = "Freed-Wu/undollar"
fetch.github = "Freed-Wu/undollar"

[manpager]
src.github = "Freed-Wu/manpager"
fetch.github = "Freed-Wu/manpager"

[translate-shell]
src.pypi = "translate-shell"
fetch.pypi = "translate-shell"

[lsp-tree-sitter]
src.pypi = "lsp-tree-sitter"
fetch.pypi = "lsp-tree-sitter"

[autotools-language-server]
src.pypi = "autotools_language_server"
fetch.pypi = "autotools_language_server"

[expect-language-server]
src.pypi = "expect-language-server"
fetch.pypi = "expect-language-server"

[mutt-language-server]
src.pypi = "mutt-language-server"
fetch.pypi = "mutt_language_server"

[requirements-language-server]
src.pypi = "requirements_language_server"
fetch.pypi = "requirements_language_server"

[sublime-syntax-language-server]
src.pypi = "sublime-syntax-language-server"
fetch.pypi = "sublime-syntax-language-server"

[termux-language-server]
src.pypi = "termux_language_server"
fetch.pypi = "termux_language_server"

[tmux-language-server]
src.pypi = "tmux_language_server"
fetch.pypi = "tmux_language_server"

[tree-sitter-muttrc]
src.pypi = "tree_sitter_muttrc"
fetch.pypi = "tree-sitter-muttrc"

[tree-sitter-tmux]
src.pypi = "tree_sitter_tmux"
fetch.pypi = "tree-sitter-tmux"

[tree-sitter-zathurarc]
src.pypi = "tree_sitter_zathurarc"
fetch.pypi = "tree_sitter_zathurarc"

[tree-sitter-requirements]
src.pypi = "tree_sitter_requirements"
fetch.pypi = "tree-sitter-requirements"

[tree-sitter-languages]
src.github_tag = "grantjenks/py-tree-sitter-languages"
fetch.github = "grantjenks/py-tree-sitter-languages"

[xilinx-language-server]
src.pypi = "xilinx-language-server"
fetch.pypi = "xilinx-language-server"

[zathura-language-server]
src.pypi = "zathura_language_server"
fetch.pypi = "zathura_language_server"

[mulimgviewer]
src.pypi = "mulimgviewer"
fetch.pypi = "mulimgviewer"
