[help2man]
src.pypi = "help2man"
fetch.pypi = "help2man"

[setuptools-generate]
src.pypi = "setuptools-generate"
fetch.pypi = "setuptools-generate"

[repl-python-wakatime]
src.pypi = "repl-python-wakatime"
fetch.pypi = "repl-python-wakatime"

[repl-python-codestats]
src.pypi = "repl-python-codestats"
fetch.pypi = "repl-python-codestats"

[translate-shell]
src.pypi = "translate-shell"
fetch.pypi = "translate-shell"

[mulimgviewer]
src.pypi = "mulimgviewer"
fetch.pypi = "mulimgviewer"

[g3kb-switch]
src.github = "lyokha/g3kb-switch"
fetch.github = "lyokha/g3kb-switch"
