[help2man]
src.pypi = "help2man"
fetch.pypi = "help2man"

[setuptools-generate]
src.pypi = "setuptools-generate"
fetch.pypi = "setuptools-generate"

[repl-python-wakatime]
src.pypi = "repl-python-wakatime"
fetch.pypi = "repl-python-wakatime"

[translate-shell]
src.pypi = "translate-shell"
fetch.pypi = "translate-shell"

[mulimgviewer]
src.pypi = "mulimgviewer"
fetch.pypi = "mulimgviewer"

[qq-nt-x86_64-linux]
src.manual = "3.1.2_12912"
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_amd64.deb"

[qq-nt-aarch64-linux]
src.manual = "3.1.2_12912"
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_arm64.deb"
