# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  help2man = {
    pname = "help2man";
    version = "0.0.9";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/help2man/help2man-0.0.9.tar.gz";
      sha256 = "sha256-V/oY7VnulJUqI0EVPq40/JACDLTrsmzopzJDNBGc+Bo=";
    };
  };
  mulimgviewer = {
    pname = "mulimgviewer";
    version = "3.9.10";
    src = fetchurl {
      url = "https://pypi.io/packages/source/m/mulimgviewer/mulimgviewer-3.9.10.tar.gz";
      sha256 = "sha256-srBgon7/yrbvV6m0Em67iiA1KLo6b2QTJjN786bZIck=";
    };
  };
  qq-nt-aarch64-linux = {
    pname = "qq-nt-aarch64-linux";
    version = "3.1.2_12912";
    src = fetchurl {
      url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_arm64.deb";
      sha256 = "sha256-5n4T0mlfEh9/84wUYiH437R95Qz6/SKDq/AK6baiW24=";
    };
  };
  qq-nt-x86_64-linux = {
    pname = "qq-nt-x86_64-linux";
    version = "3.1.2_12912";
    src = fetchurl {
      url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_amd64.deb";
      sha256 = "sha256-F+zIHqYWKiCHYNJZ5hRw0rzltizjuqhVxbpzQGagoZ0=";
    };
  };
  repl-python-wakatime = {
    pname = "repl-python-wakatime";
    version = "0.0.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/r/repl-python-wakatime/repl-python-wakatime-0.0.6.tar.gz";
      sha256 = "sha256-s2UelniMn4+wWILbVIIKidRCFaOvo/nNNofA7yf2+9c=";
    };
  };
  setuptools-generate = {
    pname = "setuptools-generate";
    version = "0.0.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/s/setuptools-generate/setuptools-generate-0.0.6.tar.gz";
      sha256 = "sha256-biMkHZ7P39355QpJXzCStgvjym9KXhFsjD5/K2RrpyU=";
    };
  };
  translate-shell = {
    pname = "translate-shell";
    version = "0.0.24";
    src = fetchurl {
      url = "https://pypi.io/packages/source/t/translate-shell/translate-shell-0.0.24.tar.gz";
      sha256 = "sha256-shlROigpKfpg/KXNA7vz8b3lM/MPPH+QNTpmjrpY480=";
    };
  };
}
